eureka:
  client:
    serviceUrl:
      defaultZone:
        http://eureka-server:8010/eureka/,http://eureka-server-primary:8011/eureka/,http://eureka-server-secondary:8012/eureka/,http://eureka-server-tertiary:8013/eureka/

---
spring:
  config.activate.on-profile: subject
  application:
    name: eureka-subject
words: I,You,He,She,It

---
spring:
  config.activate.on-profile: verb
  application:
    name: eureka-verb
words: ran,knew,had,saw,bought

---
spring:
  config.activate.on-profile: article
  application:
    name: eureka-article
words: a,the

---
spring:
  config.activate.on-profile: adjective
  application:
    name: eureka-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  config.activate.on-profile: noun
  application:
    name: eureka-noun
words: boat,book,vote,seat,backpack,partition,groundhog