eureka:
  client:
    serviceUrl:
      defaultZone:
        http://eureka-server:8761/eureka/

---
spring:
  config.activate.on-profile: subject
  application:
    name: lab-4-subject  
words: I,You,He,She,It
  
---
spring:
  config.activate.on-profile: verb
  application:
    name: lab-4-verb  
words: ran,knew,had,saw,bought

---
spring:
  config.activate.on-profile: article
  application:
    name: lab-4-article  
words: a,the

---
spring:
  config.activate.on-profile: adjective
  application:
    name: lab-4-adjective  
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  config.activate.on-profile: noun
  application:
    name: lab-4-noun  
words: boat,book,vote,seat,backpack,partition,groundhog
